import Link from "next/link";
import { products } from "@/data/products";
import { ProductCard } from "@/components/ProductCard";

export default function HomePage() {
  return <>
    <section className="hero"><div className="container"><div className="row align-items-center g-5"><div className="col-lg-7"><div className="hero-copy"><span className="eyebrow">A little greener, every day</span><h1 className="mt-3">Bring nature home.</h1><p className="mt-4">Thoughtfully chosen plants, simple care guidance, and everything you need to make your space feel alive.</p><div className="d-flex flex-wrap gap-2 mt-4"><Link href="/shop" className="btn btn-verdea">Explore the plants <i className="bi bi-arrow-right ms-2" /></Link><Link href="/plant-care" className="btn btn-outline-verdea">Learn plant care</Link></div></div></div><div className="col-lg-5"><div className="hero-plant" aria-label="Decorative plant illustration"><i className="bi bi-flower1" /></div></div></div></div></section>

    <section className="section"><div className="container"><div className="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4"><div><span className="eyebrow">Meet the collection</span><h2 className="section-title mt-2 mb-2">Plants worth growing.</h2><p className="section-subtitle mb-0">A small V1 collection for bright desks, quiet corners, and first-time plant parents.</p></div><Link href="/shop" className="btn btn-outline-verdea">View all</Link></div><div className="row g-4">{products.slice(0, 3).map((product) => <div className="col-md-4" key={product.id}><ProductCard product={product} /></div>)}</div></div></section>

    <section className="section section-soft"><div className="container"><div className="row g-4"><div className="col-lg-5"><span className="eyebrow">More than a shop</span><h2 className="section-title mt-2">Find a plant you can actually care for.</h2><p className="section-subtitle">Every Verdea product includes practical information about light, watering, temperature, size, pets, and stock so you can choose with confidence.</p><Link href="/plant-care" className="btn btn-verdea mt-2">Read the care guide</Link></div><div className="col-lg-7"><div className="row g-3"><div className="col-sm-6"><div className="info-card"><div className="info-icon"><i className="bi bi-sun" /></div><h3 className="h5 mt-4">Know the light</h3><p className="text-secondary mb-0">See exactly how much light each plant prefers.</p></div></div><div className="col-sm-6"><div className="info-card"><div className="info-icon"><i className="bi bi-droplet" /></div><h3 className="h5 mt-4">Water smarter</h3><p className="text-secondary mb-0">Simple watering guidance without the guesswork.</p></div></div><div className="col-sm-6"><div className="info-card"><div className="info-icon"><i className="bi bi-heart" /></div><h3 className="h5 mt-4">Pet-aware choices</h3><p className="text-secondary mb-0">Filter the collection by pet-friendly plants.</p></div></div><div className="col-sm-6"><div className="info-card"><div className="info-icon"><i className="bi bi-stars" /></div><h3 className="h5 mt-4">Beginner friendly</h3><p className="text-secondary mb-0">Start small with resilient plants made for learning.</p></div></div></div></div></div></div></section>
  </>;
}
